import './css/style.css'

import { Montserrat } from 'next/font/google'

import Header from '@/components/ui/header'
import Banner from '@/components/banner'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// const montserrat = Montserrat({ subsets: ['latin'], display: 'swap',weight: ['400', '700','900'], })

const montserrat = Montserrat({ subsets: ['latin'], display: 'swap',weight: ['400', '700'], })


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={montserrat.className}>
    <body className={`antialiased bg-blend-multiply bg-gray-500 bg-fixed text-gray-200 tracking-tight`} style={{ backgroundImage: "url('/images/BACK-01.png')" }}>
        <div className="flex flex-col min-h-screen overflow-hidden">
          <Header />
          {children}
        </div>
      </body>
    </html>
  )
}
 