import './css/style.css';
import { Montserrat } from 'next/font/google';
import ClientWrapper from '@/components/ClientWrapper';
import { ReactNode } from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const montserrat = Montserrat({ subsets: ['latin'], display: 'swap', weight: ['400', '700'] });

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
      <html lang="en" className={montserrat.className}>
      <body
          className={`antialiasing bg-blend-multiply bg-gray-500 bg-fixed text-gray-200 tracking-tight`}
          style={{ backgroundImage: "url('/images/BACK-01.png')" }}
      >
      <ClientWrapper>{children}</ClientWrapper>
      </body>
      </html>
  );
}